"""PEAD on 8-K earnings releases (ZT add-on strategy template ``pead_8k``).

build_run.py writes this file into a VT run directory with ``EVENTS`` and the
parameters filled in from ZT's pitdb warehouse at the run's as-of; the table
is data (literals only, as VT's signal-engine sandbox requires), not code.

Timing, per event:

* the decision instant is the later of the 8-K Item 2.02 acceptance and the
  SUE's knowledge time (the 10-Q/10-K that first reported the quarter's EPS);
* the decision bar is the first session whose close is strictly after that
  instant (16:00 New York, 13:00 on early-close days) -- so a release
  accepted after the close is never traded on its own session's bar;
* the signal is on for ``HOLD_SESSIONS`` bars from the decision bar; VT shifts
  every signal by one bar, so the position is filled at the next session's
  open and held ``HOLD_SESSIONS`` sessions.

Long the ``LONG_BUCKETS`` SUE buckets, short the ``SHORT_BUCKETS`` (empty by
default), each position at ``SLOT_WEIGHT`` of equity. A research backtest
only: orders are never placed from here.
"""

from typing import Dict

import pandas as pd

from src.quantlib.event_study import first_session_after, session_close_times

#: Generated by build_run.py: one dict per usable Item 2.02 release with
#: ``ticker``, ``accession``, ``accepted_utc``, ``sue_known_utc``, ``sue`` and
#: ``bucket``. Empty in the template.
EVENTS = ()
HOLD_SESSIONS = 20
LONG_BUCKETS = ("Q5",)
SHORT_BUCKETS = ()
SLOT_WEIGHT = 0.1


def _ticker(code: str) -> str:
    text = str(code).strip().upper()
    return text[:-3] if text.endswith(".US") else text


def decision_instant(event: dict) -> pd.Timestamp:
    """The later of the 8-K acceptance and the SUE knowledge time (UTC)."""
    accepted = pd.Timestamp(event["accepted_utc"])
    known = pd.Timestamp(event["sue_known_utc"])
    return max(accepted, known)


class SignalEngine:
    """Hold the top SUE bucket for a fixed number of sessions after each release."""

    def __init__(self, hold_sessions: int = 0, slot_weight: float = 0.0) -> None:
        """Parameters default to the generated module constants.

        Args:
            hold_sessions: Sessions to hold; 0 means ``HOLD_SESSIONS``.
            slot_weight: Weight per position; 0 means ``SLOT_WEIGHT``.
        """
        self.hold_sessions = int(hold_sessions or HOLD_SESSIONS)
        self.slot_weight = float(slot_weight or SLOT_WEIGHT)
        if self.hold_sessions < 1 or not 0.0 < self.slot_weight <= 1.0:
            raise ValueError("hold_sessions must be >= 1 and slot_weight in (0, 1]")

    def generate(self, data_map: Dict[str, pd.DataFrame]) -> Dict[str, pd.Series]:
        """Target weights per code on each code's own session calendar.

        Args:
            data_map: ``{code: OHLCV frame}`` indexed by session date.

        Returns:
            ``{code: weight Series}``; 0 outside holding windows.
        """
        by_ticker: Dict[str, list] = {}
        for event in EVENTS:
            by_ticker.setdefault(str(event["ticker"]).upper(), []).append(event)
        signals: Dict[str, pd.Series] = {}
        for code, frame in data_map.items():
            index = frame.index
            signal = pd.Series(0.0, index=index)
            events = by_ticker.get(_ticker(code), [])
            if events and len(index):
                closes = session_close_times(index)
                for event in sorted(events, key=decision_instant):
                    bucket = event.get("bucket")
                    if bucket in LONG_BUCKETS:
                        side = 1.0
                    elif bucket in SHORT_BUCKETS:
                        side = -1.0
                    else:
                        continue
                    position = int(first_session_after([decision_instant(event)], closes)[0])
                    if position < 0:
                        continue
                    signal.iloc[position:position + self.hold_sessions] = side * self.slot_weight
            signals[code] = signal
        return signals
